SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `trialdb`.`T_LOCATIONS`;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `trialdb`.`T_LOCATIONS`
(`LOCATION_DESCRIPTION`)
VALUES
('LEFT');

INSERT INTO `trialdb`.`T_LOCATIONS`
(`LOCATION_DESCRIPTION`)
VALUES
('RIGHT');

INSERT INTO `trialdb`.`T_LOCATIONS`
(`LOCATION_DESCRIPTION`)
VALUES
('LEFT&RIGHT');

INSERT INTO `trialdb`.`T_LOCATIONS`
(`LOCATION_DESCRIPTION`)
VALUES
('UP');

INSERT INTO `trialdb`.`T_LOCATIONS`
(`LOCATION_DESCRIPTION`)
VALUES
('DOWN');