SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `trialdb`.`T_SUB_TASK_TYPE`;
SET FOREIGN_KEY_CHECKS = 1;


INSERT INTO `trialdb`.`T_SUB_TASK_TYPE`
(`SUB_TASK_TYPE_DESCRIPTION`)
VALUES
('Neutral');

INSERT INTO `trialdb`.`T_SUB_TASK_TYPE`
(`SUB_TASK_TYPE_DESCRIPTION`)
VALUES
('Valid/InValid');