SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `trialdb`.`T_STIMULI`;
SET FOREIGN_KEY_CHECKS = 1;


INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('CIRCLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('TRIANGLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('UP_ARROW');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('DOWN_ARROW');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('RED_SQUARE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BLUE_SQUARE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('GREEN_SQUARE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('YELLOW_SQUARE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('RED_CIRCLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BLUE_CIRCLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('GREEN_CIRCLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('YELLOW_CIRCLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('RED_TRIANGLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BLUE_TRIANGLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('GREEN_TRIANGLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('YELLOW_TRIANGLE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('RED_STAR');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BLUE_STAR');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('GREEN_STAR');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('YELLOW_STAR');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('NA');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('NE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('NI');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('NU');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BA');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BE');

INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BI');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('BU');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('SA');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('SE');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('SI');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('SU');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('TA');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('TE');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('TI');
INSERT INTO `trialdb`.`T_STIMULI`
(`STIMULUS_DESCRIPTION`)
VALUES
('TU');
