SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `trialdb`.`T_TRIAL_INSTRUCTIONS`;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `trialdb`.`T_TRIAL_INSTRUCTIONS`
(`TRIAL_INSTRUCTION_DESCRIPTION`)
VALUES
("Attention To Location"
);
INSERT INTO `trialdb`.`T_TRIAL_INSTRUCTIONS`
(`TRIAL_INSTRUCTION_DESCRIPTION`)
VALUES
("Attention To Direction"
);
