CREATE TABLE `temp_researches` (
  `RESEARCH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RESEARCH_NAME` varchar(45) DEFAULT NULL,
  `RESEARCH_OWNER` varchar(45) DEFAULT NULL,
  `RESEARCH_DESCRIPTION` varchar(45) DEFAULT NULL,
  `RESEARCH_LOCATION_ID` int(11) DEFAULT NULL,
  `RESEARCH_COMPUTER_ID` int(11) DEFAULT NULL,
  `RESEARCH_COMPUTER_SIZE` int(11) DEFAULT NULL,
  PRIMARY KEY (`RESEARCH_ID`),
  KEY `fk_TEMP_RESEARCHES_T_RESEARCH_LOCATION1` (`RESEARCH_LOCATION_ID`),
  KEY `fk_TEMP_RESEARCHES_T_RESEARCH_COMPUTER1` (`RESEARCH_COMPUTER_ID`),
  CONSTRAINT `fk_TEMP_RESEARCHES_T_RESEARCH_COMPUTER1` FOREIGN KEY (`RESEARCH_COMPUTER_ID`) REFERENCES `t_research_computer` (`RESEARCH_COMPUTER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_RESEARCHES_T_RESEARCH_LOCATION1` FOREIGN KEY (`RESEARCH_LOCATION_ID`) REFERENCES `t_research_location` (`RESEARCH_LOCATION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=hebrew;

CREATE TABLE `temp_subjects` (
  `SUBJECT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUBJECT_IDENTIFIER` varchar(45) NOT NULL,
  `SUBJECT_NAME` varchar(45) DEFAULT NULL,
  `AGE_GROUP_ID` int(11) DEFAULT NULL,
  `AGE` float DEFAULT NULL,
  `GENDER` char(1) DEFAULT NULL,
  `DOMINANT_HAND` char(1) DEFAULT NULL,
  `CONTROL` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`SUBJECT_ID`),
  KEY `fk_temp_subjects_t_age_groups1` (`AGE_GROUP_ID`),
  CONSTRAINT `fk_temp_subjects_t_age_groups1` FOREIGN KEY (`AGE_GROUP_ID`) REFERENCES `t_age_groups` (`AGE_GROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=hebrew;

CREATE TABLE `temp_task_run` (
  `TASK_RUN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RESEARCH_ID` int(11) DEFAULT NULL,
  `TASK_ID` int(11) NOT NULL,
  `SUBJECT_ID` int(11) NOT NULL,
  `EXPERIMENTER_ID` varchar(60) DEFAULT NULL,
  `TASK_RUN_DATE` date NOT NULL,
  `IS_CONTROL_GROUP` tinyint(1) DEFAULT NULL,
  `TARGET_POPULATION_DESCRIPTION` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`TASK_RUN_ID`),
  UNIQUE KEY `unique` (`RESEARCH_ID`,`SUBJECT_ID`,`TASK_ID`),
  KEY `fk_TEMP_TASK_RUN_TEMP_SUBJECTS1` (`SUBJECT_ID`),
  KEY `fk_TEMP_TASK_RUN_TEMP_RESEARCHES1` (`RESEARCH_ID`),
  KEY `fk_TEMP_TASK_RUN_T_TASKS1` (`TASK_ID`),
  CONSTRAINT `fk_TEMP_TASK_RUN_TEMP_RESEARCHES1` FOREIGN KEY (`RESEARCH_ID`) REFERENCES `temp_researches` (`RESEARCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_TASK_RUN_TEMP_SUBJECTS1` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `temp_subjects` (`SUBJECT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_TASK_RUN_T_TASKS1` FOREIGN KEY (`TASK_ID`) REFERENCES `t_tasks` (`TASK_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=hebrew;

CREATE TABLE `temp_trial` (
  `TRIAL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TASK_RUN_ID` int(11) NOT NULL,
  `RT` int(11) DEFAULT NULL,
  `ACCURACY` tinyint(1) DEFAULT NULL,
  `STIMULUS_ID` int(11) DEFAULT NULL,
  `INPUT` varchar(20) DEFAULT NULL,
  `VALIDITY` tinyint(1) DEFAULT NULL,
  `CONGRUENCY` tinyint(1) DEFAULT NULL,
  `DELAY_BEFORE_STEP` int(11) DEFAULT NULL,
  `NUM_OF_DISTRACTORS` int(11) DEFAULT NULL,
  `IS_TARGET` tinyint(1) DEFAULT NULL,
  `PRECUE_LOCATION` int(11) DEFAULT NULL,
  `STIMULUS_LOCATION` int(11) DEFAULT NULL,
  `BLOCK_NO` int(11) DEFAULT NULL,
  `SUB_TASK_TYPE` int(11) DEFAULT NULL,
  `TRIAL_INSTRUCTIONS` int(11) DEFAULT NULL,
  PRIMARY KEY (`TRIAL_ID`),
  KEY `fk_TEMP_TRIAL_T_STIMULI` (`STIMULUS_ID`),
  KEY `fk_TEMP_TRIAL_T_TASK_RUN1` (`TASK_RUN_ID`),
  KEY `fk_TEMP_TRIAL_T_LOCATIONS1` (`PRECUE_LOCATION`),
  KEY `fk_TEMP_TRIAL_T_LOCATIONS2` (`STIMULUS_LOCATION`),
  KEY `fk_TEMP_TRIAL_T_TRIAL_INSTRUCTIONS1` (`TRIAL_INSTRUCTIONS`),
  KEY `fk_TEMP_TRIAL_T_SUB_TASK_TYPE1` (`SUB_TASK_TYPE`),
  CONSTRAINT `fk_TEMP_TRIAL_T_LOCATIONS1` FOREIGN KEY (`PRECUE_LOCATION`) REFERENCES `t_locations` (`LOCATION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_TRIAL_T_LOCATIONS2` FOREIGN KEY (`STIMULUS_LOCATION`) REFERENCES `t_locations` (`LOCATION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_TRIAL_T_STIMULI` FOREIGN KEY (`STIMULUS_ID`) REFERENCES `t_stimuli` (`STIMULUS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_TRIAL_T_SUB_TASK_TYPE1` FOREIGN KEY (`SUB_TASK_TYPE`) REFERENCES `t_sub_task_type` (`SUB_TASK_TYPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_TRIAL_TEMP_TASK_RUN1` FOREIGN KEY (`TASK_RUN_ID`) REFERENCES `temp_task_run` (`TASK_RUN_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEMP_TRIAL_T_TRIAL_INSTRUCTIONS1` FOREIGN KEY (`TRIAL_INSTRUCTIONS`) REFERENCES `t_trial_instructions` (`TRIAL_INSTRUCTION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=hebrew;
